package org.example.idDataTypeSparkExample.shared

object Columns {
  val _id = "id"
  val _id_1 = "id_1"
  val _start_id = "start_id"
  val _end_id = "end_id"
  val _step = "step"
  val _id_uuid = "id_uuid"
  val _id_bigint = "id_bigint"
  val _id_string = "id_string"
  val _id_decimal = "id_decimal"
  val _id_ts = "id_ts"
  val _type_name = "type_name"
  val _size_mb = "size_mb"
  val _size_mb_pcnt = "size_mb_pcnt"
  val _size_status = "size_status"
  val _size_mb_target = "size_mb_target"
  val _duration_s = "duration_s"
  val _duration_s_pcnt = "duration_s_pcnt"
  val _duration_target = "duration_target"
  val _count_rows = "count_rows"
  val _count_distinct_id = "count_distinct_id"
  val _avg_id = "avg_id"
  val _log_dt = "log_dt"
  val _log_dt_end = "log_dt_end"
  val _file_format = "file_format"
  val _file_compression = "file_compression"
  val _join_status = "join_status"

}
